First commit
paulshaun-kdtk/Microverse_Proffessional_Portifolio pull request #1
Opened 2023-06-01 14:16 UTC by paulshaun-kdtk

-This is the first commit to the microverse portfolio project.
-it includes an html and css file which are the main files of the project.
-it also includes eslint files which are configured to check the html and the css files.

2023-06-01 15:06 UTC, franclobo requested changes
Hi @paulshaun-kdtk, 

# Required Changes ♻️

![so-close-jim-halpert](https://github.com/paulshaun-kdtk/Microverse_Proffessiona_Portifolio/assets/58642949/4e4cc7f7-5d7b-4022-b3a4-83ccbbff3fcc)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 
- Good UI ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] In the future please 🙏🏽 commit each change with a meaningful message "First commit" is not descriptive, it is for professional documentation.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 15:06 UTC, franclobo commented on styles.css
> +}
- [ ] Please 🙏🏽 use the correct font family "Roboto" to be similar to the Figma template.

2023-06-01 15:06 UTC, franclobo commented on styles.css
> +}
- [ ] Kindly use the correct font family "Poppins" to be similar to the Figma template.

2023-06-02 09:43 UTC, Ofarouq310 requested changes
Hi @paulshaun-kdtk, ✋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🥈 

![giphy](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/102612396/41a5d5b8-b0f4-4613-9a33-876de7ccf0f8)

 ## Highlights
✅ Followed GiHub workflow.
✅ No linters errors.
✅ Good README file.

 ## Required Changes ♻️

- [ ] **As required by the previous reviewer, please stick to the `Figma` design as much as possible (e.g. font, colors, images, text, margins), it is very important for the sake of your practice.**

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 09:43 UTC, Ofarouq310 commented on MIT.md
> +
[OPTIONAL] 
- [ ] Kindly edit the `LICENSE` to hold your name.
```suggestion
## Copyright 2023, Shaun K

```

2023-06-02 09:43 UTC, Ofarouq310 commented on index.html
> +</header>
- [ ] As requested by the previous reviewer, your header still did not meet the `Figma`'s, it is still missing the `hamburger` icon, then, you have to lay out the `logo` and the `hamburger icon` using `flexbox` on the `nav` tags with paddings, Final look must be:

  ![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/102612396/f2da39a5-4613-437f-8aa0-083b5f1b74da)

2023-06-02 09:43 UTC, Ofarouq310 commented on index.html
> +
- [ ] As requested by the previous reviewer, you should use `Figma`'s background in your project, as you can see, it is broken because you did not include it in your project files.

  ![Screenshot 2023-06-02 121600](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/102612396/11f3e4a1-8971-4522-a6c7-33a218ea90ce)

2023-06-02 09:43 UTC, Ofarouq310 commented on index.html
> +    </div>
[OPTIONAL]
- [ ] Instead of using the bkg as a standalone in your HTML as `img` tag, it would be much easier if you used it as a `background-image` in your CSS for the whole section.

2023-06-02 09:43 UTC, Ofarouq310 commented on index.html
> +        </div>
- [ ] As requested by the previous reviewer, kindly note that you have to use a list (`ul` and `li`) to lay your icons instead of using `div`, this will be more professional, and more appropriate as a semantic structure, so, the list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag)

2023-06-02 11:12 UTC, vickymarz requested changes
Hi @paulshaun-kdtk 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 11:12 UTC, vickymarz commented on index.html
> +<body>
- [ ] Good job adding the background as specified by the previous reviewer, the only issue now is that the background is causing a very serious overflow which is not a good user experience. you can fix this by specifying the width to 375px i guess

![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/63473584/42065a5f-e01f-4e44-9487-17d46ef78045)
![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/63473584/31f1944f-5fab-44fc-8adb-8e9090b09dbf)

2023-06-02 11:12 UTC, vickymarz commented on styles.css
> +  display: flexbox;
- [ ] Good job trying to use Flexbox, but the correct display property is `flex`. Kindly fix it.
e.g
`display: flex;`

2023-06-02 12:51 UTC, Bantealem requested changes
Hi @paulshaun-kdtk  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)


 ## Highlights
- [x] No Linters error
- [x] correct GitHub flow 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 12:51 UTC, Bantealem commented on index.html
> +
Great job on the implementation of the previous project. But you still need some changes to make the correct design.
Currently, Your design has a `horizontal slide bar` which makes the UI unprofessional kindly fix the background image position.
Here is the Figma design
![Screenshot from 2023-06-02 15-43-20](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/101523582/c293881e-1106-436f-96ba-e94cd0917b8a)
 Here is your design
![Screenshot from 2023-06-02 15-36-27](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/101523582/1a2e149c-4d6e-4fdb-b7a5-3dee707f4fb5)

2023-06-02 16:37 UTC, paulshaun-kdtk commented on index.html
> +
I hope you guys keep in mind that we only have 3pull request reviews.... and stiill you continue to give contradictory reviews.... i do not see why the previos reviewer did not mention this but I'm starting to feel as though you guys mean for us to fail or something🚮🚮

2023-06-03 22:20 UTC, vickymarz approved these changes
Hi @paulshaun-kdtk, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Required changes finally implemented✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 06:47 UTC, merged

2023-06-05 06:53 UTC, ichala reviewed
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Project Already approved ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._