Portfolio: add a contact form and finish the mobile version
paulshaun-kdtk/Microverse_Proffessional_Portifolio pull request #3
Opened 2023-06-07 11:49 UTC by paulshaun-kdtk

This is the addition of the get in touch part of the mobile version of the portfolio project.
In this PR my group and I added a submit form where the viewers of my portfolio can get in touch with me.

2023-06-07 13:54 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @paulshaun-kdtk  👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 13:54 UTC, AbelG101 commented on index.html
> +            <form class="footer-form" action="https://formspree.io/f/mrgvwoew">
- [ ] Kindly make sure to add the attribute `method="POST"` to the form element above as the data is not being submitted properly to formspree, see the screenshot below 👇
     ![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/104968236/4cad650e-860b-41fd-a57c-179a54b32d34)

2023-06-07 13:54 UTC, AbelG101 commented on styles.css
> +}
- [ ] Ouch! this is close but as you can see from the Figma design below there's some space above and below the text "I'm always interested in..." You can easily fix that by adding a margin-top & bottom to the above selector.
- [ ] Figma design 
    ![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/104968236/33421f2d-b5f2-4198-b2d2-e743f5a0c90b)
- [ ] Your design:
    ![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/104968236/8b277e5f-d5d1-436b-acb9-cbeb508a8a3e)

2023-06-07 13:54 UTC, AbelG101 commented on styles.css
> +}
- [ ] This is very close as well, but as you can see from the Figma design the text inside the button should have a white color so please fix that
- Figma design 
  ![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/104968236/26c89c0e-30ef-4271-bd53-58a0042fb32f)
- Your design:
  ![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/104968236/320e5acf-af95-4c6f-a7c0-afc561d59a48)
- [ ] Also please make sure to implement the `:hover` & `:active` states of the button as shown in the below Figma design:
  ![firefox_PKDzK8XvCT](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/104968236/1366672e-a732-4330-8b1b-e47c9105f06a)

2023-06-07 13:54 UTC, AbelG101 commented on styles.css
> +}
- [ ] Please make sure to stick to the Figma design when styling the horizontal line here because, in the original design, the line occupies the entire width and has a color of `#DFE1E6`.
- Figma design:
  ![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/104968236/c28c78cb-2f80-4f36-87e4-563ff52ad48c)
- Your design:
  ![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/104968236/b4c8aa3d-0a04-480c-a944-1f337f580875)

2023-06-07 15:41 UTC, AbeeraTahir requested changes
# Status: Changes Required ♻️

Hi team!

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ Linter checks are passing
✔️ Good try to implement the changes suggested by the previous reviewer

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 15:41 UTC, AbeeraTahir commented on styles.css
> +
- [ ] Great effort on adding the margin from the bottom. 👍🙌 However, according to the Figma design and as mentioned by the previous reviewer, please consider adding the margin from the top as well, so that it can provide a better user experience. 😊 Please see the screenshots below, I have highlighted the margin as the rectangular border in the Figma design.

### Figma design:
![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/105105262/9794999e-b5f1-400d-8d57-2b8f9717cc6c)

### Your design:
![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/105105262/c253746b-53e1-4c8c-9f61-5aed61e78c00)

2023-06-07 15:41 UTC, AbeeraTahir commented on styles.css
> +}
- [ ] As mentioned by the previous reviewer, please add a white color to the text inside the button, as you can see in the Figma design:

### Figma design:
![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/105105262/c2b219a4-24e1-450f-a7c5-c2783173e11c)

### Your design:
![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/105105262/077499ad-c8d8-4a15-a233-eb42e8569639)

- [ ] Also, as mentioned by the previous reviewer, please apply `:hover` and `:active` state to the button, so that it will look interactive and engaging to provide a better user experience. 😊 So please implement it according to the Figma guidelines as the screenshot attached by the previous reviewer.

2023-06-07 15:41 UTC, AbeeraTahir commented on styles.css
> +}
- [ ] As mentioned by the previous reviewer, please consider giving the color of `#DFE1E6` to your horizontal line, to make sure that you stick to the Figma design to fulfill the project requirements. 😊

### Line color in Figma design:
![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/105105262/1051760b-dc96-4d25-a4ad-773e7a38de3e)


### Line color in your design:
![image](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/105105262/0b547b7a-0d37-49ed-b3a3-fba74ba872ef)

2023-06-07 15:41 UTC, AbeeraTahir commented on index.html
> +            <form class="footer-form" method="POST" action="https://formspree.io/f/mrgvwoew">
Great job on adding the `post` method to submit the form properly. 👍🙌😊

2023-06-08 08:08 UTC, LionRouge1 reviewed
Hi **Team**, 

![done](https://media.giphy.com/media/gnE4FFhtFoLKM/giphy.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linters errors, kindly make sure all the linters are passing and resubmit the project for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-08 08:30 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Team

Your project is complete! Great job  🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- form submits well
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 08:30 UTC, tufoinnkuo10 commented on index.html
> +                <input type="email" placeholder="Email Address"  name="email"   required />
- [optional] please kindly make your contact section responsive till it reaches the desktop version. you can remove the fixed width and set it to 100%.
![Screenshot (1113)_LI](https://github.com/paulshaun-kdtk/Microverse_Proffessional_Portifolio/assets/65298048/d24e6a66-cbaf-4493-9d7a-5c1bbe67eb5c)

2023-06-13 06:50 UTC, merged